### ISSUE TITLE
How to reset decoder ?

### ISSUE THREAD

**Issue by kanataxa** [lestrrat-go/msgpack#31]
すいません、日本語で失礼します。

パフォーマンスの面で、`Decode` する際に `NewDecoder` で生成した `Decoder` を使いまわしたいと考えています。

また `Decode` に失敗し `error` が返ってきた場合でも `Decoder` 自体は再利用したいと考えいるのですが、
 `Decode` がエラーなどによって途中で終了した場合、内部の `Decoder.raw` の ポジションなどの情報が古いまま残ってしまうようでした。

想定している使い方ではないかもしれませんが、この状態を回避するために外部から `Decoder.raw` ( `bufio.Reader` )をリセットするための(例えば `func (d *Decoder) Reset(r io.Reader)` のような）APIを追加していただけないでしょうか。

**Comment by kanataxa** [comment]
ざっくりとしたものではありますが、以下に実際に計測したBenchmarkコードも貼らせていただきます。

```
func BenchmarkReader_Reset(b *testing.B) {
	by := []byte("ABCDEFGHIJKLMNOPQRSTUVWUXYZ")
	b.ResetTimer()
	buf := &bytes.Buffer{}
	r := bufio.NewReader(buf)
	for i := 0; i < b.N; i++ {
		buf.Reset()
		buf.Write(by)
		r.Reset(buf)
		r.ReadByte()
	}

}

func BenchmarkReader_New(b *testing.B) {
	by := []byte("ABCDEFGHIJKLMNOPQRSTUVWUXYZ")
	b.ResetTimer()
	buf := &bytes.Buffer{}
	for i := 0; i < b.N; i++ {
		buf.Reset()
		buf.Write(by)
		r := bufio.NewReader(buf)
		r.ReadByte()
	}
}
```

```
BenchmarkReader_Reset-8         50000000                33.8 ns/op             0 B/op          0 allocs/op
BenchmarkReader_New-8            3000000               950 ns/op            4096 B/op          1 allocs/op
```

**Comment by lestrrat** [comment]
おお、それは実装し忘れですね… ちょっと内部構造を思い出すのに少し時間がかかると思いますので少々お待ちください。もし「俺さっきまでここ見てたしすぐわかるわー」という場合はPRをいただけると早いかと思います！

**Comment by lestrrat** [comment]
あー、これreaderをリセットすればいいだけなのか。なるほど。なんか他に内部状態を保持してるのかと思っちゃいました。

**Comment by kanataxa** [comment]
ご連絡ありがとうございます。

そうですね、 `bufio.Reader` が リセットできれば良いのかなと考えていました。
( また、 PRも作成させていただきました)
